--- #YAML:1.0
name:                Test-Data
version:             1.21
abstract:            Check data type properties and values
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    List::Util:                    0
    Scalar::Util:                  0
    Test::Builder:                 0
    Test::Builder::Tester:         0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
